name: Build & Release Electron

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        # Intentamos instalar en la carpeta src, que es la raíz de tu código
        run: npm install
        working-directory: ./src

      - name: Build & Publish
        # Ejecutamos el build desde la carpeta src
        run: npx electron-builder --publish always
        working-directory: ./src
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
