name: Build & Release Electron

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false # Evita que si falla Windows, se cancelen los demás
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Linux necesita estas librerías para que electron-builder no falle
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Build & Publish
        # Usamos npx para asegurar que use la versión local de electron-builder
        run: npx electron-builder --publish always
        working-directory: ./src
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
